### ISSUE TITLE
Make camera component useful (DEF-2984)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3227]
The camera component is not really useful today, which is why Blossom 2 have had to create our own camera system in order to do something reasonable with it.

Minimum what is needed to make it useful:

- [x] * DEF-2985. Camera properties should be properties that are available via go.get/set
- [x] * [DEF-2985. Camera properties should include both view and projection matrices as well as inverted versions of them.](https://github.com/defold/defold/issues/7761)
- [x] ~~* [DEF-2986. Render script should be able to get properties from any camera, by url]~~(https://github.com/defold/defold/issues/3717)
- [ ] #7763
- [x] * [DEF-2988. Editor should have a box where you can see what the camera sees.](https://github.com/defold/defold/issues/3226)
- [x] * Update documentation that says the fov is horizontal (it is actually vertical fov)

**Comment by britzl** [comment]
From #3304:

* Support for orthographic as well as perspective cameras.
* Support for different scaling models in the camera projection and viewport (keep aspect ratio intact, for instance)
* Support for multiple camera views into the render script (render several views). Might deprecate "acquire_camera_focus" message.
* Support for script reading camera transform data to allow computation of screen-space->world space (picking etc) and similar operations.

**Comment by ceruulean** [comment]
+1 ability to get the view and projection matrices. I was expecting some way to retrieve them, but could not find in docs. I have been trying to do the last bullet point: pick and select closest object in 3D.

**Comment by britzl** [comment]
> * DEF-2985. Camera properties should include both view and projection matrices as well as inverted versions of them

https://github.com/defold/defold/issues/7761

**Comment by britzl** [comment]
> * Update documentation that says the fov is horizontal (it is actually vertical fov)

Docs mention vertical fov: https://github.com/defold/doc/blob/master/docs/en/manuals/camera.md?plain=1#L34
Template has been updated: https://github.com/defold/defold/blob/dev/editor/resources/templates/template.camera#L2
