### ISSUE TITLE
Build dependency tree during a `task creation` process to avoid building of all assets

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6293]
**Task (REQUIRED):**
At the moment `bob` builds all the assets (except textures, see [this PR](https://github.com/defold/defold/pull/6129)) and then when build is done it creates dependency tree (it's much easier at this stage with already built resources) where decide what should be included into bundle and what not.

As result some errors in project's resources without any dependencies may fail build. It makes harder to have different entry point collections for different platforms, also it can take more time to build unused resources. 

**Expected outcome (REQUIRED):**
bob should create a build tree before building process.

One option is that every builder can create tasks for all the other resources it depends on starting with `game.project` as[ it's now for textures ](https://github.com/defold/defold/pull/6129)

**Comment by AGulev** [comment]
it's easier to implement step by step using `ignoreTaskAutoCreation` for builders at every step (see [example](https://github.com/defold/defold/blob/39ec316abc23aad942b15318694b4fe0b94b5df3/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/TextureBuilder.java#L31))

We should start with the core node `game.project`-> `GameProjectBuilder ` and then go down by tree.
The biggest nodes may be separated MVPs. Excluding them gives benefits itself and also makes closer the main goal.

Schematically dependency looks like that:
`Resources <- Components <- GOs <- Collections <- game.project`

We are going backwards order to prevent building for unused resources in the end.

### MVP 1 - Collections

First of all it's important to exclude collections from the current building process and then create the very first collection builder task in `GameProjectBuilder`.
All the entry points for collections are in the following places:

- [ ] `GameProjectBuilder`
- [ ] `CollectionBuilder`:
   - [ ]   embedded collections
   - [ ]   embedded collection factories
   - [ ]   embedded collection proxies
- [ ] `CollectionFactoryBuilder` (`ProtoBuilders.java`)
- [ ] `CollectionProxyBuilder` (`ProtoBuilders.java`).

### MVP 2 - GO

The next level in the dependency tree is Game Objects.

All the game objects `GameObjectBuilder` are in collections. That means that `CollectionBuilder` should create tasks for each GO.

### MVP 3 - GUI

One more big tree node are GUI components `GuiBuilder`. All the components are in Game objects `GameObjectBuilder`.

### MVP 4 - Scripts

The next step that gives valuable results is excluding scripts (see [this](https://github.com/defold/defold/issues/5427)).

All the builders for scripts are in `ScriptBuilders.java`. Basically it's the only one `LuaBuilder` with 4 entry points.

Scripts entry points:

- [ ] `render_script` is in `RenderPrototypeBuilder` (`ProtoBuilders.java`)
  - [ ] Render `RenderPrototypeBuilder`  is in  `GameProjectBuilder`
- [ ] 'script' is in `GameObjectBuilder`
- [ ] `gui_script` is in `GuiBuilder`
- [ ] `lua` is in `LuaBuilder`

**Comment by swajj** [comment]
Not sure how much effort this is to fix, but this is really making my life difficult for creating server/client builds from the same source. I want to just exclude dependencies from game.project via a custom .settings file - but bob insists on building all my .script / etc. files and complains about those missing dependencies, even though none of those files are referenced in the server build.

**Comment by swajj** [comment]
I was able to eliminate one of my unwanted dependencies via the preprocessor build extension. 

The other one (console) still causes a build failure if I try to exclude it because you have to reference `console.go` from a collection somewhere - even though I don't ultimately bundle that collection, bob still complains. And I'm assuming the preprocessor doesn't work on a .collection file :)

(note that I assume this would also speed up my server build times, which would be a lovely bonus)
