### ISSUE TITLE
New features documentation improvements

### ISSUE THREAD

**Issue by AGulev** [defold/defold#6649]
**Task (REQUIRED):**
Add info into manuals about:

- [x] defignore
- [x] meta.property
- [x] adding certs for ssl hadshake

**Comment by britzl** [comment]
Also:

- [ ] new lifecycle function on_fixed_update
- [ ] updated vsync, update freque ncy etc

**Comment by britzl** [comment]
> * meta.property

https://github.com/defold/defold/pull/6615

**Comment by britzl** [comment]
PR: https://github.com/defold/doc/pull/259
