### ISSUE TITLE
Improvement to make it clear that html5 bundle should be run using a web server

### ISSUE THREAD

**Issue by AGulev** [defold/defold#7447]
**Task (REQUIRED):**
Sometimes people don't understand that bundle should be run using a web server
There are a few suggestions to improve the situation:

- [x] In debug (only in debug?) index.html add checking for file://  in the address, if it detected show a message with a link to manual
- [ ] Add a special warning text on a bundle window for html5 about it with a ref to the manual
- [ ] show message in console when bundle is done (in bob, and now we show it in the editor as well)
- [ ] create a bat/sh file which can help to run it

**Expected outcome (REQUIRED):**
People should understand that the can't just double-click `index.html` and run the game

**Comment by AGulev** [comment]
@britzl do we really want to close this ticket?

**Comment by britzl** [comment]
> @britzl do we really want to close this ticket?

No, it was auto-closed by merging the first PR

**Comment by britzl** [comment]
@AGulev I don't think we necessarily need to do all four of those tasks? The warning on the Bundle dialog seems a bit extreme. I think the warning on the actual webpage is sufficient. We could possibly also include that launch script. With the assumption that maybe python has to be installed?

**Comment by AGulev** [comment]
@britzl I don't want to add files into the bundle folder, because it always will be a problem with uploading of the final bundle. But we can put it on a folder level, yes. 
 
Not sure about bundle dialog as well, on one hand it's going to add visibility for that, on the other hand users will get used to have it there and will ignore this text

**Comment by britzl** [comment]
> I don't want to add files into the bundle folder, because it always will be a problem with uploading of the final bundle

Good point. So maybe that warning on the index.html page itself will be enough then?

**Comment by AGulev** [comment]
> > I don't want to add files into the bundle folder, because it always will be a problem with uploading of the final bundle
> 
> Good point. So maybe that warning on the index.html page itself will be enough then?

maybe, yes. let's close it for now
