### ISSUE TITLE
Make sure that users understand how much data will be downloaded for the end user in html5 bundle

### ISSUE THREAD

**Issue by AGulev** [defold/defold#7448]
**Task (REQUIRED):**
Sometimes user make their estimations based on bundle folder size which is wrong. We should find a way to notify users about how much data the end user will download. A few suggestions: 

- [ ] Add a special warning text on a bundle window for html5 about it with a ref to the manual
- [ ] Show a message in console with the estimated downloaded size of the bundle 
- [ ] An option to build only `wasm` or only `asm` 
- [ ] Remove `asm` version of the engine fully 
- [ ] save symbols outside of the main bundle folder

**Expected outcome (REQUIRED):**
Better understanding how big the html5 Defold bundle is and how much the end user of the game will have to download.

**Comment by britzl** [comment]
I think we should focus on "An option to build only wasm or only asm" and "save symbols outside of the main bundle folder"

**Comment by AGulev** [comment]
> I think we should focus on "An option to build only wasm or only asm" and "save symbols outside of the main bundle folder"

sounds good
