### ISSUE TITLE
Update Xcode to 14.2 and iOS to 16.1

### ISSUE THREAD

**Issue by AGulev** [defold/defold#7452]
**Task (REQUIRED):**
Some libraries already use Xcode 14.2. Which means it can't be built as a Defold extension. For example https://github.com/AGulev/DefVideoAds/tree/unity-4.6

Defold must also start supporting iOS 16.1 as that is a requirement going forward. (https://developer.apple.com/news/?id=z1erkhzr)

- [ ] Package Xcode tools and iOS SDK
    - [ ] Upload to AWS
- [ ] Update build_input.yml
- [ ] Update sdk.py
- [ ] Update extender setup-standalone-server.sh

**Expected outcome (REQUIRED):**
Build for iOS 16.1 and use libs which were built using Xcode 14.2.

**Comment by Filazapovich** [comment]
Also please consider that it should be build with iOS SDK 16.1 (or above)

**Comment by JCash** [comment]
Fixed in dev+beta with https://github.com/defold/defold/pull/7480
